#version: "3"
#
#services:
#  nginx:
#    configuration : nginx_conf/student.conf
#
#  frontend:
#    image: shrustibali182/demodocker:front
#    ports:
#      - "3000:3000"
#    links:
#      - "backend"
#    depends_on:
#      - "backend"
#
#  backend:
#    image: shrustibali182/demodocker:last
#    ports:
#      - "8080:8080"


version: "3"

services:
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:80"

  backend:
#    image: shrustibali182/demodocker:last
    build:
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:80"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx_conf/student.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

